# Generated by Django 5.1.1 on 2024-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_route_route_unique_source_and_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(related_name='flights', to='airport.crew'),
        ),
    ]
