# Generated by Django 5.1.1 on 2024-10-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_flight_crew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
