# Generated by Django 5.1.1 on 2024-10-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('departure_time',)},
        ),
    ]
